### ISSUE TITLE
Plugin fails to find the worlds if using multiverse.

### ISSUE THREAD

**Issue by hashashin** [Derpy00001/MoreBosses#4]
Updating from 2.3.1 to 2.3.4 the plugin seems to fail to find the worlds as it's loaded before multiverse.
error: https://pastebin.com/ycTRbiie

Poor man's workaround: edit plugin.xml in the jar to add:
softdepend: [NordicReload, Multiverse-Core]

**Comment by Derpy00001** [comment]
Edit made to .jar file in r.2.3.4 release tag
**Download:**
https://github.com/Derpy00001/MoreBosses/releases/tag/r.2.3.4-Release

The one thing that confuses me is that line 53 of MoreBosses.java is `voidenabled=this.getConfig().getBoolean("worlds.enabled_worlds.MoreBossesVoid");`. I don't understand how this part outputs an error.
Also I'm not familiar with soft depends that much, or multiverse, so thank you for the poor man's workaround. Please let me know if it has solved the issue 😄

**Comment by hashashin** [comment]
All good now. "softdepends" afaik, just tells bukkit to load your plugin after the ones on the list. there's also "loadbefore". 
~~Not much idea of java/bukkit(just as a hobbyist), but I guess bukkit it's returning null or just erroring? as the world "dont exist" before multiverse does his stuff.~~ Nevermind that just reads your config file.

**Comment by Derpy00001** [comment]
the plugin does not require mutliverse as it loads the worlds by itself. 
Do you have `worlds.enabled_worlds.WORLDNAME` set to false? I think that the world its trying to be edited in a part of code, but its not loaded, I'll have to check my code,
but thanks for letting me know

**Comment by hashashin** [comment]
It's default config.

**Comment by hashashin** [comment]
To the record: those worlds are symlinks, forgot to mention before, perhaps it's related? They are good in v2.3.1 nevertheless.
